server:
  port: 8090

logging:
  config: classpath:log4j.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/familytree?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    #password: hxf08520215
    password: zhangcc
#  mvc:
#    view:
#      prefix: /
#      suffix: .html

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.system.liangchu.yellow.entity

##showSql
#logging:
#  level:
#    com:
#      example:
#        mapper : debug